name: retro-mike-digibyte
services:
  app:
    container_name: dgb
    image: theretromike/nodes:digibyte@sha256:70f884e76b506db720eb848df2f8c0520ad23a9c762ab1c12e69d2d65727f881
    restart: always
    volumes:
    - /media/ZimaOS-HD/NodeData/dgb:/root/.digibyte
    ports:
    - 7001:7001
    - 9001:9001
    - 12024:12024
    entrypoint: /usr/bin/digibyted
    command: -printtoconsole -server -algo=sha256d -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7001
      -rpcbind=0.0.0.0 -rpcport=9001 -rpcallowip=0.0.0.0/0 -rpcauth=pooluser:bc1f961ad347f79ab97fa7e3ac35f02a$$eb31de681359ba83be70e2cc178bf7de7b3b7affb29df2fb41907436d8ef734e
x-casaos:
  id: com.retromike.digibyte
  main: app
  icon: https://cdn.jsdelivr.net/gh/jerrykuku/ZimaOS-AppStore@gh-pages/apps/com.retromike.digibyte/assets/icon.png
  title:
    en_US: Digibyte (DGB) Node
  port_map: '8888'
