name: retro-mike-miningcore-webui-legacy
services:
  app:
    container_name: miningcorewebui_legacy
    image: theretromike/miningcorewebui:latest
    restart: always
    volumes:
    - /media/ZimaOS-HD/miningcore_legacy:/app/miningcore
    ports:
    - 82:8080
    environment:
    - API_BASE_URL=http://192.168.1.100:4001/api
    - MININGCORE_HOST=192.168.1.100
    - PLATFORM=ZIMAOS_LEGACY
    - POOL_NAME=Self-Hosted Mining Pool
    - POSTGRES_DATABASE=zimaos
    - POSTGRES_HOST=192.168.1.100
    - POSTGRES_PASSWORD=P@ssw0rd
    - POSTGRES_USER=admin
    - PUID=1000
    - STRATUM_HOST=192.168.1.100
x-casaos:
  id: com.retromike.miningcore-webui-legacy
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.miningcore-webui-legacy/assets/icon.png
  title:
    en_US: Miningcore Web UI (Legacy)
  port_map: '82'
