name: watchtower
services:
  app:
    container_name: watchtower
    image: nickfedor/watchtower:latest
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
x-casaos:
  id: com.retromike.watchtower
  main: app
  icon: https://cdn.jsdelivr.net/gh/jerrykuku/ZimaOS-AppStore@gh-pages/apps/com.retromike.watchtower/assets/icon.png
  title:
    en_US: Watchtower
  port_map: '8888'
