name: watchtower
services:
  app:
    container_name: watchtower
    image: nickfedor/watchtower:latest@sha256:38958630a4d2a663ea76c7b49c08fdaf874c2e7c00069b3b990db8b52bc5f991
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
x-casaos:
  id: com.retromike.watchtower
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.watchtower/assets/icon.png
  title:
    en_US: Watchtower
  port_map: '8888'
