name: watchtower
services:
  app:
    container_name: watchtower
    image: nickfedor/watchtower:latest@sha256:74763cf700397d760b13dcf8ff3edf76fd0b5185d809f8a1004c6698e184a4c5
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
x-casaos:
  id: com.retromike.watchtower
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.watchtower/assets/icon.png
  title:
    en_US: Watchtower
  port_map: '8888'
