name: retro-mike-wojakcoin
services:
  app:
    container_name: wjk
    image: theretromike/nodes:wojak@sha256:478b51143187f72c56e1f4b77354f7dd3cef35eff25eea04b2d4ee16b6f14459
    restart: always
    volumes:
    - /media/ZimaOS-HD/wjk:/root/.wojakcoin
    ports:
    - 7017:7017
    - 9017:9017
    command: /usr/bin/wojakcoind -printtoconsole -server -prune=550 -wallet=default
      -zmqpubhashblock=tcp://127.0.0.1:7017 -rpcbind=0.0.0.0 -rpcport=9017 -rpcallowip=0.0.0.0/0
      -rpcuser=pooluser -rpcpassword=poolpassword
x-casaos:
  id: com.retromike.wojakcoin
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.wojakcoin/assets/icon.webp
  title:
    en_US: Wojakcoin (WJK) Node
  port_map: '8888'
