name: dozzle
services:
  app:
    container_name: dozzle
    image: amir20/dozzle:v9.0.2@sha256:ead13c4e4db8fbe09e3118117dab9a8a0bf260801171ef2df2535d07c0761672
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    ports:
    - 8888:8080
x-casaos:
  id: com.retromike.dozzle
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.dozzle/assets/icon.png
  title:
    en_US: Dozzle
  port_map: '8888'
