name: retro-mike-bitcoin-ii
services:
  app:
    container_name: bc2
    image: theretromike/nodes:bitcoinii
    restart: always
    volumes:
    - /media/ZimaOS-HD/bc2:/root/.bitcoinII
    ports:
    - 7006:7006
    - 9006:9006
    command: /usr/bin/bitcoinIId -printtoconsole -server -prune=550 -wallet=default
      -zmqpubhashblock=tcp://127.0.0.1:7006 -rpcbind=0.0.0.0 -rpcport=9006 -rpcallowip=0.0.0.0/0
      -rpcuser=pooluser -rpcpassword=poolpassword
x-casaos:
  id: com.retromike.bitcoin-ii
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.bitcoin-ii/assets/icon.webp
  title:
    en_US: BitcoinII (BC2) Node
  port_map: '8888'
