name: repocket
services:
  app:
    container_name: repocket
    image: repocket/repocket:latest@sha256:90b13dfc7f85c7cfc4dc7b4e941f255ee37a047a7768de1cfa661df50a123f65
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - RP_API_KEY=xxx
    - RP_EMAIL=xxx
x-casaos:
  id: com.retromike.repocket
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.repocket/assets/icon.png
  title:
    en_US: RePocket
  index: /dashboard/share-internet
  port_map: ''
  scheme: https
