name: repocket
services:
  app:
    container_name: repocket
    image: repocket/repocket:latest@sha256:ce37ad7b6630edb6fec00316781cc760b8cce5e7e2beec969d6653ac2c4faa09
    restart: unless-stopped
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - RP_API_KEY=xxx
    - RP_EMAIL=xxx
x-casaos:
  id: com.retromike.repocket
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.repocket/assets/icon.png
  title:
    en_US: RePocket
  index: /dashboard/share-internet
  port_map: ''
  scheme: https
