name: homepage
services:
  app:
    container_name: homepage
    image: ghcr.io/gethomepage/homepage:latest@sha256:a53cc29a838858950ad3f2e93b2dbfebacbae1c1718cc7b78b1e598867f9dbc1
    restart: unless-stopped
    volumes:
    - /media/DATA/AppData/homepage:/app/config
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - HOMEPAGE_ALLOWED_HOSTS=xxx:3000
x-casaos:
  id: com.retromike.homepage
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.homepage/assets/icon.png
  title:
    en_US: Homepage
  port_map: '3000'
  scheme: http
