name: retro-mike-ravencoin
services:
  app:
    container_name: rvn
    image: theretromike/nodes:ravencoin@sha256:c74a16aabd35ca19909eab9bb04d412cc9f409862e622870d0d1b4ddc20ba882
    restart: always
    volumes:
    - /media/ZimaOS-HD/rvn:/root/.raven
    ports:
    - 7010:7010
    - 9010:9010
    command: /usr/bin/ravend -printtoconsole -server -prune=550 -wallet=default -zmqpubhashblock=tcp://127.0.0.1:7010
      -rpcbind=0.0.0.0 -rpcport=9010 -rpcallowip=0.0.0.0/0 -rpcuser=pooluser -rpcpassword=poolpassword
x-casaos:
  id: com.retromike.ravencoin
  main: app
  icon: https://cdn.jsdelivr.net/gh/jerrykuku/ZimaOS-AppStore@gh-pages/apps/com.retromike.ravencoin/assets/icon.png
  title:
    en_US: Ravencoin (RVN) Node
  port_map: '8888'
