name: retro-mike-miningcore-webui
services:
  app:
    container_name: miningcorewebui
    image: theretromike/miningcorewebui:latest@sha256:c037372c718e7985951c03daa7fe6a5fbee881727b30f4dda15984c58fb2dce3
    restart: always
    volumes:
    - /media/ZimaOS-HD/miningcore:/app/miningcore
    ports:
    - 81:8080
    environment:
    - API_BASE_URL=http://192.168.1.100:4000/api
    - MININGCORE_HOST=192.168.1.101
    - PLATFORM=ZIMAOS
    - POOL_NAME=Self-Hosted Mining Pool
    - POSTGRES_DATABASE=zimaos
    - POSTGRES_HOST=192.168.1.100
    - POSTGRES_PASSWORD=P@ssw0rd
    - POSTGRES_USER=admin
    - PUID=1000
    - STRATUM_HOST=192.168.1.100
x-casaos:
  id: com.retromike.miningcore-webui
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.miningcore-webui/assets/icon.png
  title:
    en_US: Miningcore Web UI
  port_map: '81'
