name: sshwifty
services:
  app:
    container_name: sshwifty
    image: niruix/sshwifty:latest
    restart: unless-stopped
    volumes:
      - /media/ZimaOS-HD/AppData/sshwifty/sshwifty.config.json:/sshwifty.config.json
      - /media/ZimaOS-HD/AppData/sshwifty/domain.crt:/domain.crt
      - /media/ZimaOS-HD/AppData/sshwifty/domain.key:/domain.key
    environment:
      - SSHWIFTY_CONFIG=/sshwifty.config.json
    ports:
      - 8182:8182
x-casaos:
  id: com.retromike.sshwifty
  architectures:
    - amd64
    - arm64
  main: app
  description:
    en_us: Sshwifty is a web-based ssh app that allows you to connect to SSH hosts and also have known ssh/telnet profiles for easy networked server management.
  tagline:
    en_us: Sshwifty is a web-based ssh app that allows you to connect to SSH hosts.
  developer: sshwifty
  author: Retro Mike
  icon: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtoDxxJSCew_JDIDHVqu0TH3POCyH9NQM_6g13Pch59dXSg7hlzfkNCikk&s=10
  thumbnail: ""
  title:
    en_us: Sshwifty
  category: RetroMike
  is_uncontrolled: false
  port_map: "8182"
  index: /
  scheme: https
