name: retro-mike-bitcoin-silver
services:
  app:
    container_name: btcs
    image: theretromike/nodes:bitcoinsilver
    restart: always
    volumes:
    - /media/ZimaOS-HD/btcs:/root/.bitcoinsilver
    ports:
    - 7015:7015
    - 9015:9015
    command: /usr/bin/bitcoinsilverd -printtoconsole -server -prune=550 -wallet=default
      -zmqpubhashblock=tcp://127.0.0.1:7015 -rpcbind=0.0.0.0 -rpcport=9015 -rpcallowip=0.0.0.0/0
      -rpcuser=pooluser -rpcpassword=poolpassword -addnode=89.163.242.248:10566 -addnode=95.141.241.26:10566
x-casaos:
  id: com.retromike.bitcoin-silver
  main: app
  icon: https://theretromike.github.io/retro-mike-zima-app-store/apps/com.retromike.bitcoin-silver/assets/icon
  title:
    en_US: Bitcoin Silver (BTCS) Node
  port_map: '8888'
